=== gotrecillo/dmso/characters/characters.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://www.w3schools.com"
          xmlns="http://www.w3schools.com characters.xsd"
          xmlns:xs="http://www.w3.org/2001/XMLSchema">
          
  <xs:element name="characters">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="character"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="character">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="size" type="xs:string"/>
        <xs:element name="race" type="xs:string"/>
        <xs:element name="alignement" type="xs:string"/>
        <xs:element name="ac" type="xs:string"/>
        <xs:element name="hp" type="xs:string"/>
        <xs:element name="speed" type="xs:string"/>
        <xs:element ref="stats"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="stats">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="str" type="xs:string"/>
        <xs:element name="dex" type="xs:string"/>
        <xs:element name="con" type="xs:string"/>
        <xs:element name="int" type="xs:string"/>
        <xs:element name="wis" type="xs:string"/>
        <xs:element name="cha" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== gotrecillo/dmso/characters/characters.xml
<?xml version="1.0" encoding="UTF-8"?>
<characters xmlns="http://www.w3schools.com"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.w3school.com characters.xsd">
  <character>
    <name>Jamma Gleamsilver</name>
    <size>small</size>
    <race>humanoid (gnome)</race>
    <alignement>neutral</alignement>
    <ac>15 (leather armor)</ac>
    <hp>22 (4d6+8)</hp>
    <speed>25</speed>
    <stats>
      <str>8</str>
      <dex>17</dex>
      <con>14</con>
      <int>15</int>
      <wis>10</wis>
      <cha>12</cha>
    </stats>
  </character>
</characters>
